services:
  sub-aggregator:
    build: ./sub-aggregator-service
    depends_on:
      sub-db:
        condition: service_healthy
    ports:
      - 7000:7000

  sub-db:
    image: postgres:latest
    container_name: aggregator-db
    env_file: .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./data/postgres_data:/app/data/postgres_data
    ports:
      - "5431:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5